In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [6]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
import pandas as pd
import numpy as np

In [11]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [14]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [22]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [23]:
df['target'] = dataset.target

In [24]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

## We are doing logistic reg for binary classification so remove 2 from target only 0 and 1 will be there

In [34]:
df_copy = df[df['target'] != 2]

In [36]:
df_copy

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

## Dependent and independent feature

In [39]:
X = df_copy.iloc[:,:-1]
y = df_copy.iloc[:,-1:]

In [43]:
# train test split
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
classifier = LogisticRegression()

In [47]:
classifier.fit(X_train,y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [64]:
classifier.predict_proba(X_test)

array([[0.00118085, 0.99881915],
       [0.01580857, 0.98419143],
       [0.00303433, 0.99696567],
       [0.96964813, 0.03035187],
       [0.94251523, 0.05748477],
       [0.97160984, 0.02839016],
       [0.99355615, 0.00644385],
       [0.03169836, 0.96830164],
       [0.97459743, 0.02540257],
       [0.97892756, 0.02107244],
       [0.95512297, 0.04487703],
       [0.9607199 , 0.0392801 ],
       [0.00429472, 0.99570528],
       [0.9858324 , 0.0141676 ],
       [0.00924893, 0.99075107],
       [0.98144334, 0.01855666],
       [0.00208036, 0.99791964],
       [0.00125422, 0.99874578],
       [0.97463766, 0.02536234],
       [0.96123726, 0.03876274]])

In [48]:
# Prediction
y_pred = classifier.predict(X_test)

In [52]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

### Confusion metrix ,accuracy score ,Classification report

In [54]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [58]:
confusion_matrix(y_test,y_pred)

array([[12,  0],
       [ 0,  8]])

In [59]:
accuracy_score(y_test,y_pred)

1.0

In [62]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Hyperparameter Tuning

## Grid search CV

In [66]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore') 

In [73]:
parameters = {"penalty" : ('l1','l2','elasticnet',None),"C" : [1,10],"solver" : ['lbfgs','liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']}

In [74]:
clf = GridSearchCV(classifier,param_grid=parameters,cv = 5)

#### Splitting of train data atp trainand validation data


In [77]:
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10],
                         'penalty': ('l1', 'l2', 'elasticnet', None),
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']})

### Best parameters


In [79]:
clf.best_params_

{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}

### Now create your classifier by own accorfing to best parameters

In [80]:
classifier = LogisticRegression(penalty='l1',C = 1.0,solver='liblinear')

In [81]:
classifier.fit(X_train,y_train)

LogisticRegression(penalty='l1', solver='liblinear')

In [83]:
y_pred = classifier.predict(X_test)

In [84]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [85]:
confusion_matrix(y_test,y_pred)

array([[12,  0],
       [ 0,  8]])

In [86]:
accuracy_score(y_test,y_pred)

1.0

In [88]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



### Randomized search CV

In [89]:
from sklearn.model_selection import RandomizedSearchCV

In [99]:
random_clf = RandomizedSearchCV(classifier,param_distributions=parameters,cv = 5,n_iter=100)

In [100]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5,
                   estimator=LogisticRegression(penalty='l1',
                                                solver='liblinear'),
                   n_iter=100,
                   param_distributions={'C': [1, 10],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None),
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']})

In [101]:
random_clf.best_params_

{'solver': 'liblinear', 'penalty': 'l1', 'C': 1}

### Now craete model with these parameters for best accuracy

In [102]:
classifier = LogisticRegression(penalty='l1',C = 1,solver='liblinear')

In [103]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [105]:
y_pred = classifier.predict(X_test)

In [106]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [107]:
confusion_matrix(y_test,y_pred)

array([[12,  0],
       [ 0,  8]])

In [108]:
accuracy_score(y_test,y_pred)

1.0

In [109]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

